# ── Projektmetadaten ────────────────────────────────────────
projekt:
  git_repository: dq_artikelstammdaten
  version: "1.0"
  autor: Anna Sommani
  datum: "2026-04-13"
  beschreibung: "Datenqualitaetsanalyse Artikelstammdaten dm-drogerie markt"
# ── Datei ────────────────────────────────────────────────────
datei:
  filename: "Recruiting_Aufgabe_Data_Analyst_08_25.xlsx"

# ── Tabellenblatter ──────────────────────────────────────────
# key: Python-Variable, value: Excel-Blattname
tabellen:
  artikeldaten_grunddaten: "Artikeldaten Grunddaten"
  kategorisierung:         "Kategorisierung"
  preise:                  "Preise"
  werksdaten:              "Werksdaten"
  lieferantendaten:        "Lieferantendaten"

# ── Export ───────────────────────────────────────────────────
export:
  dpi: 600
  save_png: false  # Ob die Tabellen auch als PNG-Bilder gespeichert werden sollen (für Präsentationen / fast visuelle Darstellung)
# ── Checks to run ───────────────────────────────────────────────────
normalization:
  check_1nf: false

