# ── Projektmetadaten ────────────────────────────────────────
projekt:
  git_repository: dq_artikelstammdaten
  autor: Anna Sommani
# ── Datei ────────────────────────────────────────────────────
datei:
  filename: "dq_artikelstammdaten.xlsx"

# ── Tabellenblatter ──────────────────────────────────────────
# key: Python-Variable, value: Excel-Blattname
tabellen:
  artikeldaten_grunddaten: "Artikeldaten Grunddaten"
  kategorisierung:         "Kategorisierung"
  preise:                  "Preise"
  werksdaten:              "Werksdaten"
  lieferantendaten:        "Lieferantendaten"

# ── Export ───────────────────────────────────────────────────
export:
  dpi: 600
  save_png: false  # Ob die Tabellen auch als PNG-Bilder gespeichert werden sollen (für Präsentationen / fast visuelle Darstellung)
# ── Checks to run ───────────────────────────────────────────────────
normalization:
  check_1nf: false

extra_checks:
  plausibilitaet_masse: true
  gtin_format: true
  validitaet_vokabular: true
  artikel_ohne_werksdaten: true

